# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField()),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(verbose_name='date created')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
